### ISSUE TITLE
Passing username as a query param is deprecated

### ISSUE THREAD

**Issue by NasaGeek** [flightaware/tcl-jira-api#2]
Seems to work on our Jira Cloud instance for now, but it could break at any time. We should be passing `accountId` (or some other noted alternative) instead for endpoints like `/rest/api/2/user` and probably `/rest/api/2/user/search`.

**Comment by pclifton** [comment]
Addressed by https://github.com/flightaware/tcl-jira-api/commit/784f89d269c61e0e6d04c79829bea07942403e28. It appears there was only one spot where we were depending on the "old" way of doing user lookups.
